// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/perception/lidar/lib/scene_manager/ground_service/proto/ground_service_config.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2flidar_2flib_2fscene_5fmanager_2fground_5fservice_2fproto_2fground_5fservice_5fconfig_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2flidar_2flib_2fscene_5fmanager_2fground_5fservice_2fproto_2fground_5fservice_5fconfig_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_modules_2fperception_2flidar_2flib_2fscene_5fmanager_2fground_5fservice_2fproto_2fground_5fservice_5fconfig_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_modules_2fperception_2flidar_2flib_2fscene_5fmanager_2fground_5fservice_2fproto_2fground_5fservice_5fconfig_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fperception_2flidar_2flib_2fscene_5fmanager_2fground_5fservice_2fproto_2fground_5fservice_5fconfig_2eproto;
namespace apollo {
namespace perception {
namespace lidar {
class GroundServiceConfig;
struct GroundServiceConfigDefaultTypeInternal;
extern GroundServiceConfigDefaultTypeInternal _GroundServiceConfig_default_instance_;
}  // namespace lidar
}  // namespace perception
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::perception::lidar::GroundServiceConfig* Arena::CreateMaybeMessage<::apollo::perception::lidar::GroundServiceConfig>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace perception {
namespace lidar {

// ===================================================================

class GroundServiceConfig final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.perception.lidar.GroundServiceConfig) */ {
 public:
  inline GroundServiceConfig() : GroundServiceConfig(nullptr) {}
  ~GroundServiceConfig() override;
  explicit PROTOBUF_CONSTEXPR GroundServiceConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GroundServiceConfig(const GroundServiceConfig& from);
  GroundServiceConfig(GroundServiceConfig&& from) noexcept
    : GroundServiceConfig() {
    *this = ::std::move(from);
  }

  inline GroundServiceConfig& operator=(const GroundServiceConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline GroundServiceConfig& operator=(GroundServiceConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GroundServiceConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const GroundServiceConfig* internal_default_instance() {
    return reinterpret_cast<const GroundServiceConfig*>(
               &_GroundServiceConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GroundServiceConfig& a, GroundServiceConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(GroundServiceConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GroundServiceConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GroundServiceConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GroundServiceConfig>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GroundServiceConfig& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GroundServiceConfig& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GroundServiceConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.perception.lidar.GroundServiceConfig";
  }
  protected:
  explicit GroundServiceConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGridSizeFieldNumber = 3,
    kRoiRadXFieldNumber = 1,
    kRoiRadYFieldNumber = 2,
  };
  // optional uint32 grid_size = 3 [default = 16];
  bool has_grid_size() const;
  private:
  bool _internal_has_grid_size() const;
  public:
  void clear_grid_size();
  uint32_t grid_size() const;
  void set_grid_size(uint32_t value);
  private:
  uint32_t _internal_grid_size() const;
  void _internal_set_grid_size(uint32_t value);
  public:

  // optional double roi_rad_x = 1 [default = 120];
  bool has_roi_rad_x() const;
  private:
  bool _internal_has_roi_rad_x() const;
  public:
  void clear_roi_rad_x();
  double roi_rad_x() const;
  void set_roi_rad_x(double value);
  private:
  double _internal_roi_rad_x() const;
  void _internal_set_roi_rad_x(double value);
  public:

  // optional double roi_rad_y = 2 [default = 120];
  bool has_roi_rad_y() const;
  private:
  bool _internal_has_roi_rad_y() const;
  public:
  void clear_roi_rad_y();
  double roi_rad_y() const;
  void set_roi_rad_y(double value);
  private:
  double _internal_roi_rad_y() const;
  void _internal_set_roi_rad_y(double value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.perception.lidar.GroundServiceConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t grid_size_;
    double roi_rad_x_;
    double roi_rad_y_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_modules_2fperception_2flidar_2flib_2fscene_5fmanager_2fground_5fservice_2fproto_2fground_5fservice_5fconfig_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GroundServiceConfig

// optional double roi_rad_x = 1 [default = 120];
inline bool GroundServiceConfig::_internal_has_roi_rad_x() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool GroundServiceConfig::has_roi_rad_x() const {
  return _internal_has_roi_rad_x();
}
inline void GroundServiceConfig::clear_roi_rad_x() {
  _impl_.roi_rad_x_ = 120;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline double GroundServiceConfig::_internal_roi_rad_x() const {
  return _impl_.roi_rad_x_;
}
inline double GroundServiceConfig::roi_rad_x() const {
  // @@protoc_insertion_point(field_get:apollo.perception.lidar.GroundServiceConfig.roi_rad_x)
  return _internal_roi_rad_x();
}
inline void GroundServiceConfig::_internal_set_roi_rad_x(double value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.roi_rad_x_ = value;
}
inline void GroundServiceConfig::set_roi_rad_x(double value) {
  _internal_set_roi_rad_x(value);
  // @@protoc_insertion_point(field_set:apollo.perception.lidar.GroundServiceConfig.roi_rad_x)
}

// optional double roi_rad_y = 2 [default = 120];
inline bool GroundServiceConfig::_internal_has_roi_rad_y() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool GroundServiceConfig::has_roi_rad_y() const {
  return _internal_has_roi_rad_y();
}
inline void GroundServiceConfig::clear_roi_rad_y() {
  _impl_.roi_rad_y_ = 120;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double GroundServiceConfig::_internal_roi_rad_y() const {
  return _impl_.roi_rad_y_;
}
inline double GroundServiceConfig::roi_rad_y() const {
  // @@protoc_insertion_point(field_get:apollo.perception.lidar.GroundServiceConfig.roi_rad_y)
  return _internal_roi_rad_y();
}
inline void GroundServiceConfig::_internal_set_roi_rad_y(double value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.roi_rad_y_ = value;
}
inline void GroundServiceConfig::set_roi_rad_y(double value) {
  _internal_set_roi_rad_y(value);
  // @@protoc_insertion_point(field_set:apollo.perception.lidar.GroundServiceConfig.roi_rad_y)
}

// optional uint32 grid_size = 3 [default = 16];
inline bool GroundServiceConfig::_internal_has_grid_size() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool GroundServiceConfig::has_grid_size() const {
  return _internal_has_grid_size();
}
inline void GroundServiceConfig::clear_grid_size() {
  _impl_.grid_size_ = 16u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t GroundServiceConfig::_internal_grid_size() const {
  return _impl_.grid_size_;
}
inline uint32_t GroundServiceConfig::grid_size() const {
  // @@protoc_insertion_point(field_get:apollo.perception.lidar.GroundServiceConfig.grid_size)
  return _internal_grid_size();
}
inline void GroundServiceConfig::_internal_set_grid_size(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.grid_size_ = value;
}
inline void GroundServiceConfig::set_grid_size(uint32_t value) {
  _internal_set_grid_size(value);
  // @@protoc_insertion_point(field_set:apollo.perception.lidar.GroundServiceConfig.grid_size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace lidar
}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2flidar_2flib_2fscene_5fmanager_2fground_5fservice_2fproto_2fground_5fservice_5fconfig_2eproto
