// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/perception/camera/common/proto/object_template_meta_schema.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto;
namespace apollo {
namespace perception {
namespace camera {
class Dim;
struct DimDefaultTypeInternal;
extern DimDefaultTypeInternal _Dim_default_instance_;
class ObjectTemplate;
struct ObjectTemplateDefaultTypeInternal;
extern ObjectTemplateDefaultTypeInternal _ObjectTemplate_default_instance_;
class ObjectTemplateMeta;
struct ObjectTemplateMetaDefaultTypeInternal;
extern ObjectTemplateMetaDefaultTypeInternal _ObjectTemplateMeta_default_instance_;
}  // namespace camera
}  // namespace perception
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::perception::camera::Dim* Arena::CreateMaybeMessage<::apollo::perception::camera::Dim>(Arena*);
template<> ::apollo::perception::camera::ObjectTemplate* Arena::CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(Arena*);
template<> ::apollo::perception::camera::ObjectTemplateMeta* Arena::CreateMaybeMessage<::apollo::perception::camera::ObjectTemplateMeta>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace perception {
namespace camera {

// ===================================================================

class Dim final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.perception.camera.Dim) */ {
 public:
  inline Dim() : Dim(nullptr) {}
  ~Dim() override;
  explicit PROTOBUF_CONSTEXPR Dim(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Dim(const Dim& from);
  Dim(Dim&& from) noexcept
    : Dim() {
    *this = ::std::move(from);
  }

  inline Dim& operator=(const Dim& from) {
    CopyFrom(from);
    return *this;
  }
  inline Dim& operator=(Dim&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Dim& default_instance() {
    return *internal_default_instance();
  }
  static inline const Dim* internal_default_instance() {
    return reinterpret_cast<const Dim*>(
               &_Dim_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Dim& a, Dim& b) {
    a.Swap(&b);
  }
  inline void Swap(Dim* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Dim* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Dim* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Dim>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Dim& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Dim& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Dim* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.perception.camera.Dim";
  }
  protected:
  explicit Dim(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHFieldNumber = 1,
    kWFieldNumber = 2,
    kLFieldNumber = 3,
  };
  // optional float H = 1;
  bool has_h() const;
  private:
  bool _internal_has_h() const;
  public:
  void clear_h();
  float h() const;
  void set_h(float value);
  private:
  float _internal_h() const;
  void _internal_set_h(float value);
  public:

  // optional float W = 2;
  bool has_w() const;
  private:
  bool _internal_has_w() const;
  public:
  void clear_w();
  float w() const;
  void set_w(float value);
  private:
  float _internal_w() const;
  void _internal_set_w(float value);
  public:

  // optional float L = 3;
  bool has_l() const;
  private:
  bool _internal_has_l() const;
  public:
  void clear_l();
  float l() const;
  void set_l(float value);
  private:
  float _internal_l() const;
  void _internal_set_l(float value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.perception.camera.Dim)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    float h_;
    float w_;
    float l_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto;
};
// -------------------------------------------------------------------

class ObjectTemplate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.perception.camera.ObjectTemplate) */ {
 public:
  inline ObjectTemplate() : ObjectTemplate(nullptr) {}
  ~ObjectTemplate() override;
  explicit PROTOBUF_CONSTEXPR ObjectTemplate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectTemplate(const ObjectTemplate& from);
  ObjectTemplate(ObjectTemplate&& from) noexcept
    : ObjectTemplate() {
    *this = ::std::move(from);
  }

  inline ObjectTemplate& operator=(const ObjectTemplate& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectTemplate& operator=(ObjectTemplate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectTemplate& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectTemplate* internal_default_instance() {
    return reinterpret_cast<const ObjectTemplate*>(
               &_ObjectTemplate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ObjectTemplate& a, ObjectTemplate& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectTemplate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectTemplate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectTemplate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectTemplate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectTemplate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ObjectTemplate& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectTemplate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.perception.camera.ObjectTemplate";
  }
  protected:
  explicit ObjectTemplate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDimFieldNumber = 2,
    kSpeedLimitFieldNumber = 1,
  };
  // repeated .apollo.perception.camera.Dim dim = 2;
  int dim_size() const;
  private:
  int _internal_dim_size() const;
  public:
  void clear_dim();
  ::apollo::perception::camera::Dim* mutable_dim(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::perception::camera::Dim >*
      mutable_dim();
  private:
  const ::apollo::perception::camera::Dim& _internal_dim(int index) const;
  ::apollo::perception::camera::Dim* _internal_add_dim();
  public:
  const ::apollo::perception::camera::Dim& dim(int index) const;
  ::apollo::perception::camera::Dim* add_dim();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::perception::camera::Dim >&
      dim() const;

  // optional float speed_limit = 1;
  bool has_speed_limit() const;
  private:
  bool _internal_has_speed_limit() const;
  public:
  void clear_speed_limit();
  float speed_limit() const;
  void set_speed_limit(float value);
  private:
  float _internal_speed_limit() const;
  void _internal_set_speed_limit(float value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.perception.camera.ObjectTemplate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::perception::camera::Dim > dim_;
    float speed_limit_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto;
};
// -------------------------------------------------------------------

class ObjectTemplateMeta final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.perception.camera.ObjectTemplateMeta) */ {
 public:
  inline ObjectTemplateMeta() : ObjectTemplateMeta(nullptr) {}
  ~ObjectTemplateMeta() override;
  explicit PROTOBUF_CONSTEXPR ObjectTemplateMeta(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectTemplateMeta(const ObjectTemplateMeta& from);
  ObjectTemplateMeta(ObjectTemplateMeta&& from) noexcept
    : ObjectTemplateMeta() {
    *this = ::std::move(from);
  }

  inline ObjectTemplateMeta& operator=(const ObjectTemplateMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectTemplateMeta& operator=(ObjectTemplateMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectTemplateMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectTemplateMeta* internal_default_instance() {
    return reinterpret_cast<const ObjectTemplateMeta*>(
               &_ObjectTemplateMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ObjectTemplateMeta& a, ObjectTemplateMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectTemplateMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectTemplateMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectTemplateMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectTemplateMeta>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectTemplateMeta& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ObjectTemplateMeta& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectTemplateMeta* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.perception.camera.ObjectTemplateMeta";
  }
  protected:
  explicit ObjectTemplateMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnknownFieldNumber = 1,
    kUnknownMovableFieldNumber = 2,
    kUnknownUnmovableFieldNumber = 3,
    kCarFieldNumber = 4,
    kVanFieldNumber = 5,
    kTruckFieldNumber = 6,
    kBusFieldNumber = 7,
    kCyclistFieldNumber = 8,
    kMotorcyclistFieldNumber = 9,
    kTricyclistFieldNumber = 10,
    kPedestrianFieldNumber = 11,
    kTrafficconeFieldNumber = 12,
    kMaxDimChangeRatioFieldNumber = 21,
  };
  // optional .apollo.perception.camera.ObjectTemplate unknown = 1;
  bool has_unknown() const;
  private:
  bool _internal_has_unknown() const;
  public:
  void clear_unknown();
  const ::apollo::perception::camera::ObjectTemplate& unknown() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_unknown();
  ::apollo::perception::camera::ObjectTemplate* mutable_unknown();
  void set_allocated_unknown(::apollo::perception::camera::ObjectTemplate* unknown);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_unknown() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_unknown();
  public:
  void unsafe_arena_set_allocated_unknown(
      ::apollo::perception::camera::ObjectTemplate* unknown);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_unknown();

  // optional .apollo.perception.camera.ObjectTemplate unknown_movable = 2;
  bool has_unknown_movable() const;
  private:
  bool _internal_has_unknown_movable() const;
  public:
  void clear_unknown_movable();
  const ::apollo::perception::camera::ObjectTemplate& unknown_movable() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_unknown_movable();
  ::apollo::perception::camera::ObjectTemplate* mutable_unknown_movable();
  void set_allocated_unknown_movable(::apollo::perception::camera::ObjectTemplate* unknown_movable);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_unknown_movable() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_unknown_movable();
  public:
  void unsafe_arena_set_allocated_unknown_movable(
      ::apollo::perception::camera::ObjectTemplate* unknown_movable);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_unknown_movable();

  // optional .apollo.perception.camera.ObjectTemplate unknown_unmovable = 3;
  bool has_unknown_unmovable() const;
  private:
  bool _internal_has_unknown_unmovable() const;
  public:
  void clear_unknown_unmovable();
  const ::apollo::perception::camera::ObjectTemplate& unknown_unmovable() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_unknown_unmovable();
  ::apollo::perception::camera::ObjectTemplate* mutable_unknown_unmovable();
  void set_allocated_unknown_unmovable(::apollo::perception::camera::ObjectTemplate* unknown_unmovable);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_unknown_unmovable() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_unknown_unmovable();
  public:
  void unsafe_arena_set_allocated_unknown_unmovable(
      ::apollo::perception::camera::ObjectTemplate* unknown_unmovable);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_unknown_unmovable();

  // optional .apollo.perception.camera.ObjectTemplate car = 4;
  bool has_car() const;
  private:
  bool _internal_has_car() const;
  public:
  void clear_car();
  const ::apollo::perception::camera::ObjectTemplate& car() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_car();
  ::apollo::perception::camera::ObjectTemplate* mutable_car();
  void set_allocated_car(::apollo::perception::camera::ObjectTemplate* car);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_car() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_car();
  public:
  void unsafe_arena_set_allocated_car(
      ::apollo::perception::camera::ObjectTemplate* car);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_car();

  // optional .apollo.perception.camera.ObjectTemplate van = 5;
  bool has_van() const;
  private:
  bool _internal_has_van() const;
  public:
  void clear_van();
  const ::apollo::perception::camera::ObjectTemplate& van() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_van();
  ::apollo::perception::camera::ObjectTemplate* mutable_van();
  void set_allocated_van(::apollo::perception::camera::ObjectTemplate* van);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_van() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_van();
  public:
  void unsafe_arena_set_allocated_van(
      ::apollo::perception::camera::ObjectTemplate* van);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_van();

  // optional .apollo.perception.camera.ObjectTemplate truck = 6;
  bool has_truck() const;
  private:
  bool _internal_has_truck() const;
  public:
  void clear_truck();
  const ::apollo::perception::camera::ObjectTemplate& truck() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_truck();
  ::apollo::perception::camera::ObjectTemplate* mutable_truck();
  void set_allocated_truck(::apollo::perception::camera::ObjectTemplate* truck);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_truck() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_truck();
  public:
  void unsafe_arena_set_allocated_truck(
      ::apollo::perception::camera::ObjectTemplate* truck);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_truck();

  // optional .apollo.perception.camera.ObjectTemplate bus = 7;
  bool has_bus() const;
  private:
  bool _internal_has_bus() const;
  public:
  void clear_bus();
  const ::apollo::perception::camera::ObjectTemplate& bus() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_bus();
  ::apollo::perception::camera::ObjectTemplate* mutable_bus();
  void set_allocated_bus(::apollo::perception::camera::ObjectTemplate* bus);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_bus() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_bus();
  public:
  void unsafe_arena_set_allocated_bus(
      ::apollo::perception::camera::ObjectTemplate* bus);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_bus();

  // optional .apollo.perception.camera.ObjectTemplate cyclist = 8;
  bool has_cyclist() const;
  private:
  bool _internal_has_cyclist() const;
  public:
  void clear_cyclist();
  const ::apollo::perception::camera::ObjectTemplate& cyclist() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_cyclist();
  ::apollo::perception::camera::ObjectTemplate* mutable_cyclist();
  void set_allocated_cyclist(::apollo::perception::camera::ObjectTemplate* cyclist);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_cyclist() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_cyclist();
  public:
  void unsafe_arena_set_allocated_cyclist(
      ::apollo::perception::camera::ObjectTemplate* cyclist);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_cyclist();

  // optional .apollo.perception.camera.ObjectTemplate motorcyclist = 9;
  bool has_motorcyclist() const;
  private:
  bool _internal_has_motorcyclist() const;
  public:
  void clear_motorcyclist();
  const ::apollo::perception::camera::ObjectTemplate& motorcyclist() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_motorcyclist();
  ::apollo::perception::camera::ObjectTemplate* mutable_motorcyclist();
  void set_allocated_motorcyclist(::apollo::perception::camera::ObjectTemplate* motorcyclist);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_motorcyclist() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_motorcyclist();
  public:
  void unsafe_arena_set_allocated_motorcyclist(
      ::apollo::perception::camera::ObjectTemplate* motorcyclist);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_motorcyclist();

  // optional .apollo.perception.camera.ObjectTemplate tricyclist = 10;
  bool has_tricyclist() const;
  private:
  bool _internal_has_tricyclist() const;
  public:
  void clear_tricyclist();
  const ::apollo::perception::camera::ObjectTemplate& tricyclist() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_tricyclist();
  ::apollo::perception::camera::ObjectTemplate* mutable_tricyclist();
  void set_allocated_tricyclist(::apollo::perception::camera::ObjectTemplate* tricyclist);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_tricyclist() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_tricyclist();
  public:
  void unsafe_arena_set_allocated_tricyclist(
      ::apollo::perception::camera::ObjectTemplate* tricyclist);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_tricyclist();

  // optional .apollo.perception.camera.ObjectTemplate pedestrian = 11;
  bool has_pedestrian() const;
  private:
  bool _internal_has_pedestrian() const;
  public:
  void clear_pedestrian();
  const ::apollo::perception::camera::ObjectTemplate& pedestrian() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_pedestrian();
  ::apollo::perception::camera::ObjectTemplate* mutable_pedestrian();
  void set_allocated_pedestrian(::apollo::perception::camera::ObjectTemplate* pedestrian);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_pedestrian() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_pedestrian();
  public:
  void unsafe_arena_set_allocated_pedestrian(
      ::apollo::perception::camera::ObjectTemplate* pedestrian);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_pedestrian();

  // optional .apollo.perception.camera.ObjectTemplate trafficcone = 12;
  bool has_trafficcone() const;
  private:
  bool _internal_has_trafficcone() const;
  public:
  void clear_trafficcone();
  const ::apollo::perception::camera::ObjectTemplate& trafficcone() const;
  PROTOBUF_NODISCARD ::apollo::perception::camera::ObjectTemplate* release_trafficcone();
  ::apollo::perception::camera::ObjectTemplate* mutable_trafficcone();
  void set_allocated_trafficcone(::apollo::perception::camera::ObjectTemplate* trafficcone);
  private:
  const ::apollo::perception::camera::ObjectTemplate& _internal_trafficcone() const;
  ::apollo::perception::camera::ObjectTemplate* _internal_mutable_trafficcone();
  public:
  void unsafe_arena_set_allocated_trafficcone(
      ::apollo::perception::camera::ObjectTemplate* trafficcone);
  ::apollo::perception::camera::ObjectTemplate* unsafe_arena_release_trafficcone();

  // optional float max_dim_change_ratio = 21 [default = 0.1];
  bool has_max_dim_change_ratio() const;
  private:
  bool _internal_has_max_dim_change_ratio() const;
  public:
  void clear_max_dim_change_ratio();
  float max_dim_change_ratio() const;
  void set_max_dim_change_ratio(float value);
  private:
  float _internal_max_dim_change_ratio() const;
  void _internal_set_max_dim_change_ratio(float value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.perception.camera.ObjectTemplateMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::apollo::perception::camera::ObjectTemplate* unknown_;
    ::apollo::perception::camera::ObjectTemplate* unknown_movable_;
    ::apollo::perception::camera::ObjectTemplate* unknown_unmovable_;
    ::apollo::perception::camera::ObjectTemplate* car_;
    ::apollo::perception::camera::ObjectTemplate* van_;
    ::apollo::perception::camera::ObjectTemplate* truck_;
    ::apollo::perception::camera::ObjectTemplate* bus_;
    ::apollo::perception::camera::ObjectTemplate* cyclist_;
    ::apollo::perception::camera::ObjectTemplate* motorcyclist_;
    ::apollo::perception::camera::ObjectTemplate* tricyclist_;
    ::apollo::perception::camera::ObjectTemplate* pedestrian_;
    ::apollo::perception::camera::ObjectTemplate* trafficcone_;
    float max_dim_change_ratio_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Dim

// optional float H = 1;
inline bool Dim::_internal_has_h() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Dim::has_h() const {
  return _internal_has_h();
}
inline void Dim::clear_h() {
  _impl_.h_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float Dim::_internal_h() const {
  return _impl_.h_;
}
inline float Dim::h() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.Dim.H)
  return _internal_h();
}
inline void Dim::_internal_set_h(float value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.h_ = value;
}
inline void Dim::set_h(float value) {
  _internal_set_h(value);
  // @@protoc_insertion_point(field_set:apollo.perception.camera.Dim.H)
}

// optional float W = 2;
inline bool Dim::_internal_has_w() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Dim::has_w() const {
  return _internal_has_w();
}
inline void Dim::clear_w() {
  _impl_.w_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float Dim::_internal_w() const {
  return _impl_.w_;
}
inline float Dim::w() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.Dim.W)
  return _internal_w();
}
inline void Dim::_internal_set_w(float value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.w_ = value;
}
inline void Dim::set_w(float value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:apollo.perception.camera.Dim.W)
}

// optional float L = 3;
inline bool Dim::_internal_has_l() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Dim::has_l() const {
  return _internal_has_l();
}
inline void Dim::clear_l() {
  _impl_.l_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float Dim::_internal_l() const {
  return _impl_.l_;
}
inline float Dim::l() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.Dim.L)
  return _internal_l();
}
inline void Dim::_internal_set_l(float value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.l_ = value;
}
inline void Dim::set_l(float value) {
  _internal_set_l(value);
  // @@protoc_insertion_point(field_set:apollo.perception.camera.Dim.L)
}

// -------------------------------------------------------------------

// ObjectTemplate

// optional float speed_limit = 1;
inline bool ObjectTemplate::_internal_has_speed_limit() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ObjectTemplate::has_speed_limit() const {
  return _internal_has_speed_limit();
}
inline void ObjectTemplate::clear_speed_limit() {
  _impl_.speed_limit_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float ObjectTemplate::_internal_speed_limit() const {
  return _impl_.speed_limit_;
}
inline float ObjectTemplate::speed_limit() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplate.speed_limit)
  return _internal_speed_limit();
}
inline void ObjectTemplate::_internal_set_speed_limit(float value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.speed_limit_ = value;
}
inline void ObjectTemplate::set_speed_limit(float value) {
  _internal_set_speed_limit(value);
  // @@protoc_insertion_point(field_set:apollo.perception.camera.ObjectTemplate.speed_limit)
}

// repeated .apollo.perception.camera.Dim dim = 2;
inline int ObjectTemplate::_internal_dim_size() const {
  return _impl_.dim_.size();
}
inline int ObjectTemplate::dim_size() const {
  return _internal_dim_size();
}
inline void ObjectTemplate::clear_dim() {
  _impl_.dim_.Clear();
}
inline ::apollo::perception::camera::Dim* ObjectTemplate::mutable_dim(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplate.dim)
  return _impl_.dim_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::perception::camera::Dim >*
ObjectTemplate::mutable_dim() {
  // @@protoc_insertion_point(field_mutable_list:apollo.perception.camera.ObjectTemplate.dim)
  return &_impl_.dim_;
}
inline const ::apollo::perception::camera::Dim& ObjectTemplate::_internal_dim(int index) const {
  return _impl_.dim_.Get(index);
}
inline const ::apollo::perception::camera::Dim& ObjectTemplate::dim(int index) const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplate.dim)
  return _internal_dim(index);
}
inline ::apollo::perception::camera::Dim* ObjectTemplate::_internal_add_dim() {
  return _impl_.dim_.Add();
}
inline ::apollo::perception::camera::Dim* ObjectTemplate::add_dim() {
  ::apollo::perception::camera::Dim* _add = _internal_add_dim();
  // @@protoc_insertion_point(field_add:apollo.perception.camera.ObjectTemplate.dim)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::apollo::perception::camera::Dim >&
ObjectTemplate::dim() const {
  // @@protoc_insertion_point(field_list:apollo.perception.camera.ObjectTemplate.dim)
  return _impl_.dim_;
}

// -------------------------------------------------------------------

// ObjectTemplateMeta

// optional .apollo.perception.camera.ObjectTemplate unknown = 1;
inline bool ObjectTemplateMeta::_internal_has_unknown() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.unknown_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_unknown() const {
  return _internal_has_unknown();
}
inline void ObjectTemplateMeta::clear_unknown() {
  if (_impl_.unknown_ != nullptr) _impl_.unknown_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_unknown() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.unknown_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::unknown() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.unknown)
  return _internal_unknown();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_unknown(
    ::apollo::perception::camera::ObjectTemplate* unknown) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.unknown_);
  }
  _impl_.unknown_ = unknown;
  if (unknown) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.unknown)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_unknown() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.unknown_;
  _impl_.unknown_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_unknown() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.unknown)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.unknown_;
  _impl_.unknown_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_unknown() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.unknown_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.unknown_ = p;
  }
  return _impl_.unknown_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_unknown() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_unknown();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.unknown)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_unknown(::apollo::perception::camera::ObjectTemplate* unknown) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.unknown_;
  }
  if (unknown) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(unknown);
    if (message_arena != submessage_arena) {
      unknown = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, unknown, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.unknown_ = unknown;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.unknown)
}

// optional .apollo.perception.camera.ObjectTemplate unknown_movable = 2;
inline bool ObjectTemplateMeta::_internal_has_unknown_movable() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.unknown_movable_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_unknown_movable() const {
  return _internal_has_unknown_movable();
}
inline void ObjectTemplateMeta::clear_unknown_movable() {
  if (_impl_.unknown_movable_ != nullptr) _impl_.unknown_movable_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_unknown_movable() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.unknown_movable_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::unknown_movable() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.unknown_movable)
  return _internal_unknown_movable();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_unknown_movable(
    ::apollo::perception::camera::ObjectTemplate* unknown_movable) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.unknown_movable_);
  }
  _impl_.unknown_movable_ = unknown_movable;
  if (unknown_movable) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.unknown_movable)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_unknown_movable() {
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.unknown_movable_;
  _impl_.unknown_movable_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_unknown_movable() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.unknown_movable)
  _impl_._has_bits_[0] &= ~0x00000002u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.unknown_movable_;
  _impl_.unknown_movable_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_unknown_movable() {
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.unknown_movable_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.unknown_movable_ = p;
  }
  return _impl_.unknown_movable_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_unknown_movable() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_unknown_movable();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.unknown_movable)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_unknown_movable(::apollo::perception::camera::ObjectTemplate* unknown_movable) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.unknown_movable_;
  }
  if (unknown_movable) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(unknown_movable);
    if (message_arena != submessage_arena) {
      unknown_movable = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, unknown_movable, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.unknown_movable_ = unknown_movable;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.unknown_movable)
}

// optional .apollo.perception.camera.ObjectTemplate unknown_unmovable = 3;
inline bool ObjectTemplateMeta::_internal_has_unknown_unmovable() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.unknown_unmovable_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_unknown_unmovable() const {
  return _internal_has_unknown_unmovable();
}
inline void ObjectTemplateMeta::clear_unknown_unmovable() {
  if (_impl_.unknown_unmovable_ != nullptr) _impl_.unknown_unmovable_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_unknown_unmovable() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.unknown_unmovable_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::unknown_unmovable() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.unknown_unmovable)
  return _internal_unknown_unmovable();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_unknown_unmovable(
    ::apollo::perception::camera::ObjectTemplate* unknown_unmovable) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.unknown_unmovable_);
  }
  _impl_.unknown_unmovable_ = unknown_unmovable;
  if (unknown_unmovable) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.unknown_unmovable)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_unknown_unmovable() {
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.unknown_unmovable_;
  _impl_.unknown_unmovable_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_unknown_unmovable() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.unknown_unmovable)
  _impl_._has_bits_[0] &= ~0x00000004u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.unknown_unmovable_;
  _impl_.unknown_unmovable_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_unknown_unmovable() {
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.unknown_unmovable_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.unknown_unmovable_ = p;
  }
  return _impl_.unknown_unmovable_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_unknown_unmovable() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_unknown_unmovable();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.unknown_unmovable)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_unknown_unmovable(::apollo::perception::camera::ObjectTemplate* unknown_unmovable) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.unknown_unmovable_;
  }
  if (unknown_unmovable) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(unknown_unmovable);
    if (message_arena != submessage_arena) {
      unknown_unmovable = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, unknown_unmovable, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.unknown_unmovable_ = unknown_unmovable;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.unknown_unmovable)
}

// optional .apollo.perception.camera.ObjectTemplate car = 4;
inline bool ObjectTemplateMeta::_internal_has_car() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.car_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_car() const {
  return _internal_has_car();
}
inline void ObjectTemplateMeta::clear_car() {
  if (_impl_.car_ != nullptr) _impl_.car_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_car() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.car_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::car() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.car)
  return _internal_car();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_car(
    ::apollo::perception::camera::ObjectTemplate* car) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.car_);
  }
  _impl_.car_ = car;
  if (car) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.car)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_car() {
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.car_;
  _impl_.car_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_car() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.car)
  _impl_._has_bits_[0] &= ~0x00000008u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.car_;
  _impl_.car_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_car() {
  _impl_._has_bits_[0] |= 0x00000008u;
  if (_impl_.car_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.car_ = p;
  }
  return _impl_.car_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_car() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_car();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.car)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_car(::apollo::perception::camera::ObjectTemplate* car) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.car_;
  }
  if (car) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(car);
    if (message_arena != submessage_arena) {
      car = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, car, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.car_ = car;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.car)
}

// optional .apollo.perception.camera.ObjectTemplate van = 5;
inline bool ObjectTemplateMeta::_internal_has_van() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.van_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_van() const {
  return _internal_has_van();
}
inline void ObjectTemplateMeta::clear_van() {
  if (_impl_.van_ != nullptr) _impl_.van_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_van() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.van_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::van() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.van)
  return _internal_van();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_van(
    ::apollo::perception::camera::ObjectTemplate* van) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.van_);
  }
  _impl_.van_ = van;
  if (van) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.van)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_van() {
  _impl_._has_bits_[0] &= ~0x00000010u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.van_;
  _impl_.van_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_van() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.van)
  _impl_._has_bits_[0] &= ~0x00000010u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.van_;
  _impl_.van_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_van() {
  _impl_._has_bits_[0] |= 0x00000010u;
  if (_impl_.van_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.van_ = p;
  }
  return _impl_.van_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_van() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_van();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.van)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_van(::apollo::perception::camera::ObjectTemplate* van) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.van_;
  }
  if (van) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(van);
    if (message_arena != submessage_arena) {
      van = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, van, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.van_ = van;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.van)
}

// optional .apollo.perception.camera.ObjectTemplate truck = 6;
inline bool ObjectTemplateMeta::_internal_has_truck() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.truck_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_truck() const {
  return _internal_has_truck();
}
inline void ObjectTemplateMeta::clear_truck() {
  if (_impl_.truck_ != nullptr) _impl_.truck_->Clear();
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_truck() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.truck_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::truck() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.truck)
  return _internal_truck();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_truck(
    ::apollo::perception::camera::ObjectTemplate* truck) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.truck_);
  }
  _impl_.truck_ = truck;
  if (truck) {
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.truck)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_truck() {
  _impl_._has_bits_[0] &= ~0x00000020u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.truck_;
  _impl_.truck_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_truck() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.truck)
  _impl_._has_bits_[0] &= ~0x00000020u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.truck_;
  _impl_.truck_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_truck() {
  _impl_._has_bits_[0] |= 0x00000020u;
  if (_impl_.truck_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.truck_ = p;
  }
  return _impl_.truck_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_truck() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_truck();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.truck)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_truck(::apollo::perception::camera::ObjectTemplate* truck) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.truck_;
  }
  if (truck) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(truck);
    if (message_arena != submessage_arena) {
      truck = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, truck, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000020u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000020u;
  }
  _impl_.truck_ = truck;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.truck)
}

// optional .apollo.perception.camera.ObjectTemplate bus = 7;
inline bool ObjectTemplateMeta::_internal_has_bus() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.bus_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_bus() const {
  return _internal_has_bus();
}
inline void ObjectTemplateMeta::clear_bus() {
  if (_impl_.bus_ != nullptr) _impl_.bus_->Clear();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_bus() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.bus_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::bus() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.bus)
  return _internal_bus();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_bus(
    ::apollo::perception::camera::ObjectTemplate* bus) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.bus_);
  }
  _impl_.bus_ = bus;
  if (bus) {
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.bus)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_bus() {
  _impl_._has_bits_[0] &= ~0x00000040u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.bus_;
  _impl_.bus_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_bus() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.bus)
  _impl_._has_bits_[0] &= ~0x00000040u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.bus_;
  _impl_.bus_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_bus() {
  _impl_._has_bits_[0] |= 0x00000040u;
  if (_impl_.bus_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.bus_ = p;
  }
  return _impl_.bus_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_bus() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_bus();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.bus)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_bus(::apollo::perception::camera::ObjectTemplate* bus) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.bus_;
  }
  if (bus) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(bus);
    if (message_arena != submessage_arena) {
      bus = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bus, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000040u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000040u;
  }
  _impl_.bus_ = bus;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.bus)
}

// optional .apollo.perception.camera.ObjectTemplate cyclist = 8;
inline bool ObjectTemplateMeta::_internal_has_cyclist() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.cyclist_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_cyclist() const {
  return _internal_has_cyclist();
}
inline void ObjectTemplateMeta::clear_cyclist() {
  if (_impl_.cyclist_ != nullptr) _impl_.cyclist_->Clear();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_cyclist() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.cyclist_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::cyclist() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.cyclist)
  return _internal_cyclist();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_cyclist(
    ::apollo::perception::camera::ObjectTemplate* cyclist) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.cyclist_);
  }
  _impl_.cyclist_ = cyclist;
  if (cyclist) {
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.cyclist)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_cyclist() {
  _impl_._has_bits_[0] &= ~0x00000080u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.cyclist_;
  _impl_.cyclist_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_cyclist() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.cyclist)
  _impl_._has_bits_[0] &= ~0x00000080u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.cyclist_;
  _impl_.cyclist_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_cyclist() {
  _impl_._has_bits_[0] |= 0x00000080u;
  if (_impl_.cyclist_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.cyclist_ = p;
  }
  return _impl_.cyclist_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_cyclist() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_cyclist();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.cyclist)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_cyclist(::apollo::perception::camera::ObjectTemplate* cyclist) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.cyclist_;
  }
  if (cyclist) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(cyclist);
    if (message_arena != submessage_arena) {
      cyclist = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, cyclist, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000080u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000080u;
  }
  _impl_.cyclist_ = cyclist;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.cyclist)
}

// optional .apollo.perception.camera.ObjectTemplate motorcyclist = 9;
inline bool ObjectTemplateMeta::_internal_has_motorcyclist() const {
  bool value = (_impl_._has_bits_[0] & 0x00000100u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.motorcyclist_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_motorcyclist() const {
  return _internal_has_motorcyclist();
}
inline void ObjectTemplateMeta::clear_motorcyclist() {
  if (_impl_.motorcyclist_ != nullptr) _impl_.motorcyclist_->Clear();
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_motorcyclist() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.motorcyclist_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::motorcyclist() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.motorcyclist)
  return _internal_motorcyclist();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_motorcyclist(
    ::apollo::perception::camera::ObjectTemplate* motorcyclist) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.motorcyclist_);
  }
  _impl_.motorcyclist_ = motorcyclist;
  if (motorcyclist) {
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.motorcyclist)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_motorcyclist() {
  _impl_._has_bits_[0] &= ~0x00000100u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.motorcyclist_;
  _impl_.motorcyclist_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_motorcyclist() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.motorcyclist)
  _impl_._has_bits_[0] &= ~0x00000100u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.motorcyclist_;
  _impl_.motorcyclist_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_motorcyclist() {
  _impl_._has_bits_[0] |= 0x00000100u;
  if (_impl_.motorcyclist_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.motorcyclist_ = p;
  }
  return _impl_.motorcyclist_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_motorcyclist() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_motorcyclist();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.motorcyclist)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_motorcyclist(::apollo::perception::camera::ObjectTemplate* motorcyclist) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.motorcyclist_;
  }
  if (motorcyclist) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(motorcyclist);
    if (message_arena != submessage_arena) {
      motorcyclist = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, motorcyclist, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000100u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000100u;
  }
  _impl_.motorcyclist_ = motorcyclist;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.motorcyclist)
}

// optional .apollo.perception.camera.ObjectTemplate tricyclist = 10;
inline bool ObjectTemplateMeta::_internal_has_tricyclist() const {
  bool value = (_impl_._has_bits_[0] & 0x00000200u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.tricyclist_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_tricyclist() const {
  return _internal_has_tricyclist();
}
inline void ObjectTemplateMeta::clear_tricyclist() {
  if (_impl_.tricyclist_ != nullptr) _impl_.tricyclist_->Clear();
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_tricyclist() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.tricyclist_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::tricyclist() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.tricyclist)
  return _internal_tricyclist();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_tricyclist(
    ::apollo::perception::camera::ObjectTemplate* tricyclist) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.tricyclist_);
  }
  _impl_.tricyclist_ = tricyclist;
  if (tricyclist) {
    _impl_._has_bits_[0] |= 0x00000200u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000200u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.tricyclist)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_tricyclist() {
  _impl_._has_bits_[0] &= ~0x00000200u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.tricyclist_;
  _impl_.tricyclist_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_tricyclist() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.tricyclist)
  _impl_._has_bits_[0] &= ~0x00000200u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.tricyclist_;
  _impl_.tricyclist_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_tricyclist() {
  _impl_._has_bits_[0] |= 0x00000200u;
  if (_impl_.tricyclist_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.tricyclist_ = p;
  }
  return _impl_.tricyclist_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_tricyclist() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_tricyclist();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.tricyclist)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_tricyclist(::apollo::perception::camera::ObjectTemplate* tricyclist) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.tricyclist_;
  }
  if (tricyclist) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(tricyclist);
    if (message_arena != submessage_arena) {
      tricyclist = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, tricyclist, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000200u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000200u;
  }
  _impl_.tricyclist_ = tricyclist;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.tricyclist)
}

// optional .apollo.perception.camera.ObjectTemplate pedestrian = 11;
inline bool ObjectTemplateMeta::_internal_has_pedestrian() const {
  bool value = (_impl_._has_bits_[0] & 0x00000400u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pedestrian_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_pedestrian() const {
  return _internal_has_pedestrian();
}
inline void ObjectTemplateMeta::clear_pedestrian() {
  if (_impl_.pedestrian_ != nullptr) _impl_.pedestrian_->Clear();
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_pedestrian() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.pedestrian_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::pedestrian() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.pedestrian)
  return _internal_pedestrian();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_pedestrian(
    ::apollo::perception::camera::ObjectTemplate* pedestrian) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pedestrian_);
  }
  _impl_.pedestrian_ = pedestrian;
  if (pedestrian) {
    _impl_._has_bits_[0] |= 0x00000400u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000400u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.pedestrian)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_pedestrian() {
  _impl_._has_bits_[0] &= ~0x00000400u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.pedestrian_;
  _impl_.pedestrian_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_pedestrian() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.pedestrian)
  _impl_._has_bits_[0] &= ~0x00000400u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.pedestrian_;
  _impl_.pedestrian_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_pedestrian() {
  _impl_._has_bits_[0] |= 0x00000400u;
  if (_impl_.pedestrian_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.pedestrian_ = p;
  }
  return _impl_.pedestrian_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_pedestrian() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_pedestrian();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.pedestrian)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_pedestrian(::apollo::perception::camera::ObjectTemplate* pedestrian) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pedestrian_;
  }
  if (pedestrian) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pedestrian);
    if (message_arena != submessage_arena) {
      pedestrian = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pedestrian, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000400u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000400u;
  }
  _impl_.pedestrian_ = pedestrian;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.pedestrian)
}

// optional .apollo.perception.camera.ObjectTemplate trafficcone = 12;
inline bool ObjectTemplateMeta::_internal_has_trafficcone() const {
  bool value = (_impl_._has_bits_[0] & 0x00000800u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.trafficcone_ != nullptr);
  return value;
}
inline bool ObjectTemplateMeta::has_trafficcone() const {
  return _internal_has_trafficcone();
}
inline void ObjectTemplateMeta::clear_trafficcone() {
  if (_impl_.trafficcone_ != nullptr) _impl_.trafficcone_->Clear();
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::_internal_trafficcone() const {
  const ::apollo::perception::camera::ObjectTemplate* p = _impl_.trafficcone_;
  return p != nullptr ? *p : reinterpret_cast<const ::apollo::perception::camera::ObjectTemplate&>(
      ::apollo::perception::camera::_ObjectTemplate_default_instance_);
}
inline const ::apollo::perception::camera::ObjectTemplate& ObjectTemplateMeta::trafficcone() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.trafficcone)
  return _internal_trafficcone();
}
inline void ObjectTemplateMeta::unsafe_arena_set_allocated_trafficcone(
    ::apollo::perception::camera::ObjectTemplate* trafficcone) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.trafficcone_);
  }
  _impl_.trafficcone_ = trafficcone;
  if (trafficcone) {
    _impl_._has_bits_[0] |= 0x00000800u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000800u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:apollo.perception.camera.ObjectTemplateMeta.trafficcone)
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::release_trafficcone() {
  _impl_._has_bits_[0] &= ~0x00000800u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.trafficcone_;
  _impl_.trafficcone_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::unsafe_arena_release_trafficcone() {
  // @@protoc_insertion_point(field_release:apollo.perception.camera.ObjectTemplateMeta.trafficcone)
  _impl_._has_bits_[0] &= ~0x00000800u;
  ::apollo::perception::camera::ObjectTemplate* temp = _impl_.trafficcone_;
  _impl_.trafficcone_ = nullptr;
  return temp;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::_internal_mutable_trafficcone() {
  _impl_._has_bits_[0] |= 0x00000800u;
  if (_impl_.trafficcone_ == nullptr) {
    auto* p = CreateMaybeMessage<::apollo::perception::camera::ObjectTemplate>(GetArenaForAllocation());
    _impl_.trafficcone_ = p;
  }
  return _impl_.trafficcone_;
}
inline ::apollo::perception::camera::ObjectTemplate* ObjectTemplateMeta::mutable_trafficcone() {
  ::apollo::perception::camera::ObjectTemplate* _msg = _internal_mutable_trafficcone();
  // @@protoc_insertion_point(field_mutable:apollo.perception.camera.ObjectTemplateMeta.trafficcone)
  return _msg;
}
inline void ObjectTemplateMeta::set_allocated_trafficcone(::apollo::perception::camera::ObjectTemplate* trafficcone) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.trafficcone_;
  }
  if (trafficcone) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(trafficcone);
    if (message_arena != submessage_arena) {
      trafficcone = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, trafficcone, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000800u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000800u;
  }
  _impl_.trafficcone_ = trafficcone;
  // @@protoc_insertion_point(field_set_allocated:apollo.perception.camera.ObjectTemplateMeta.trafficcone)
}

// optional float max_dim_change_ratio = 21 [default = 0.1];
inline bool ObjectTemplateMeta::_internal_has_max_dim_change_ratio() const {
  bool value = (_impl_._has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool ObjectTemplateMeta::has_max_dim_change_ratio() const {
  return _internal_has_max_dim_change_ratio();
}
inline void ObjectTemplateMeta::clear_max_dim_change_ratio() {
  _impl_.max_dim_change_ratio_ = 0.1f;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline float ObjectTemplateMeta::_internal_max_dim_change_ratio() const {
  return _impl_.max_dim_change_ratio_;
}
inline float ObjectTemplateMeta::max_dim_change_ratio() const {
  // @@protoc_insertion_point(field_get:apollo.perception.camera.ObjectTemplateMeta.max_dim_change_ratio)
  return _internal_max_dim_change_ratio();
}
inline void ObjectTemplateMeta::_internal_set_max_dim_change_ratio(float value) {
  _impl_._has_bits_[0] |= 0x00001000u;
  _impl_.max_dim_change_ratio_ = value;
}
inline void ObjectTemplateMeta::set_max_dim_change_ratio(float value) {
  _internal_set_max_dim_change_ratio(value);
  // @@protoc_insertion_point(field_set:apollo.perception.camera.ObjectTemplateMeta.max_dim_change_ratio)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace camera
}  // namespace perception
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_modules_2fperception_2fcamera_2fcommon_2fproto_2fobject_5ftemplate_5fmeta_5fschema_2eproto
